In [1]:
from sklearn.datasets import make_moons 
X, y = make_moons(n_samples=1000, noise=0.05, random_state=42)

In [2]:
from sklearn.cluster import DBSCAN
dbscan_clustering = DBSCAN(eps=0.05, min_samples=5)

In [3]:
dbscan_clustering.fit(X)

DBSCAN(algorithm='auto', eps=0.05, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=5, n_jobs=None, p=None)

In [4]:
anomalies = (dbscan_clustering.labels_ == -1)

In [5]:
import pandas as pd
pd_anomalies =  pd.DataFrame(anomalies)

In [6]:
pd_anomalies.value_counts() #To see how many anomalies are in the dataset

False    923
True      77
dtype: int64

In [7]:
dbscan_clustering.labels_

array([ 0,  2, -1, -1,  1,  0,  0,  0,  2,  5,  2,  3,  0,  2,  2,  2,  4,
        2,  2,  4,  0,  5,  1,  0,  5,  5,  3,  2,  2,  2,  4,  5,  0,  6,
        1, -1,  0,  0,  2,  3, -1,  3,  4, -1,  4,  4,  2,  0,  6,  2,  0,
        2,  4,  0,  3,  3,  0,  3,  5,  2, -1,  3,  0,  5,  0,  0,  0,  2,
        3,  0,  3,  6,  0,  2,  4,  4,  0,  3,  0,  4,  0,  3, -1,  3,  4,
        0, -1,  2,  2,  4,  1,  6,  0,  5,  2,  6,  2,  3,  3, -1,  2, -1,
        2,  4,  0,  0,  0,  2,  5,  2,  0,  2, -1,  2,  3,  1,  5,  2,  0,
        4,  2,  1,  2,  4,  4,  0,  0,  6,  2,  2,  0,  2, -1,  2,  0,  3,
        3,  5, -1,  3,  3,  5,  2,  4,  2,  2,  2,  4,  2,  4,  0, -1,  2,
        1,  2,  6,  4,  2,  3,  2, -1,  2,  0,  0,  2,  0,  4,  0,  4,  4,
        1,  6,  3,  2,  6,  1,  4,  4,  2,  0,  6,  0,  1,  0,  2,  5,  1,
        1,  2,  2,  2,  2,  0,  5,  5,  1,  4,  5,  0,  3,  3,  0,  0,  0,
        2,  0,  5,  2, -1,  2,  3,  5,  2,  2,  0,  4,  0,  4,  2,  2,  4,
        2,  2,  3,  2,  3

* There are to many clusters!

* Indices of the core instances

In [8]:
dbscan_clustering.core_sample_indices_

array([  0,   4,   5,   6,   7,   8,  10,  11,  12,  13,  14,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  28,  29,  30,  31,
        32,  33,  34,  36,  38,  39,  41,  42,  44,  45,  47,  49,  50,
        51,  52,  53,  54,  55,  56,  58,  59,  61,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  83,  84,  85,  87,  88,  89,  90,  91,  93,  94,  96,
        97,  98, 102, 103, 104, 105, 106, 107, 108, 109, 110, 113, 114,
       115, 116, 117, 119, 120, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 135, 136, 139, 140, 141, 143, 144, 145, 146, 147, 148, 149,
       150, 152, 153, 154, 155, 156, 157, 158, 159, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 172, 173, 174, 175, 176, 177, 178,
       179, 181, 182, 183, 185, 186, 187, 188, 189, 191, 193, 194, 195,
       196, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 209, 210,
       211, 212, 213, 214, 215, 216, 217, 218, 219, 221, 222, 22

* Core instances themselves 

In [9]:
dbscan_clustering.components_

array([[-0.02137124,  0.40618608],
       [-0.84192557,  0.53058695],
       [ 0.58930337, -0.32137599],
       ...,
       [ 1.66258462, -0.3079193 ],
       [-0.94355873,  0.3278936 ],
       [ 0.79419406,  0.60777171]])

* There are too much anomalies, lets change the "eps" hyperparameter

In [10]:
dbscan_clustering = DBSCAN(eps=0.2)

In [11]:
dbscan_clustering.fit(X)

DBSCAN(algorithm='auto', eps=0.2, leaf_size=30, metric='euclidean',
       metric_params=None, min_samples=5, n_jobs=None, p=None)

In [12]:
dbscan_clustering.labels_

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,

* Here we only have two clusters, great!
* We'll continue with this model.

* Since DBSCAN dont have any predict function, we can train some other clustering with the instances and the labels of DBSCAN. 

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)

* We'll train this model with the core instances and its labels (only the labels of the core instances)

In [14]:
knn.fit(dbscan_clustering.components_, dbscan_clustering.labels_[dbscan_clustering.core_sample_indices_]) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=50, p=2,
                     weights='uniform')

In [15]:
import numpy as np


In [16]:
X_new =  np.array([[-0.5, 0],[0,-0.5],[1,-0.1],[2,1]])

In [17]:
knn.predict(X_new)

array([1, 0, 1, 0])

In [18]:
knn.predict_proba(X_new)

array([[0.18, 0.82],
       [1.  , 0.  ],
       [0.12, 0.88],
       [1.  , 0.  ]])

In [19]:
y_dist, y_pred_idx = knn.kneighbors(X_new,n_neighbors=1 )#Returns [distances, index of the k nearest neighbors(in this case, 1 neighbor)] 

In [20]:
y_dist

array([[0.43045422],
       [0.2740511 ],
       [0.06010476],
       [0.48399468]])

In [21]:
y_pred_idx

array([[909],
       [587],
       [915],
       [231]])

In [22]:
y_pred = dbscan_clustering.labels_[dbscan_clustering.core_sample_indices_][y_pred_idx] #why the dbscan_clustering.core_sample_indices_???

In [23]:
y_pred

array([[1],
       [0],
       [1],
       [0]])

In [24]:
y_pred[y_dist>0.2] = -1 #Getting anomalies using a distance threshold

In [25]:
y_pred

array([[-1],
       [-1],
       [ 1],
       [-1]])

In [27]:
from sklearn.mixture import GaussianMixture
gm = GaussianMixture(n_components=3, n_init=10)

In [28]:
gm.fit(X)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
                means_init=None, n_components=3, n_init=10,
                precisions_init=None, random_state=None, reg_covar=1e-06,
                tol=0.001, verbose=0, verbose_interval=10, warm_start=False,
                weights_init=None)

In [30]:
gm.covariances_

array([[[ 0.16423007, -0.09776417],
        [-0.09776417,  0.28773664]],

       [[ 0.06092047,  0.06554928],
        [ 0.06554928,  0.08769601]],

       [[ 0.05368744,  0.06215896],
        [ 0.06215896,  0.08993529]]])

* For the covariances matrices, the values are:
>[ $\sigma^2_1$ , $\rho$ $\sigma_1$ $\sigma_2$] \\
>[  $\rho$ $\sigma_1$ $\sigma_2$ , $\sigma^2_2$ ]


Where: 
* $\sigma_1$ & $\sigma_2$ = Standard deviations, if you elevate the sigmas by 2, it is the covariance.
*  $\rho$ = Correlation.


In [31]:
gm.means_

array([[ 0.49392194,  0.25478715],
       [ 1.73139197, -0.0687895 ],
       [-0.74739902,  0.55611538]])

* This values are the "cordinates" of the mean of the cluster ("center")

In [32]:
gm.weights_

array([0.58801248, 0.20846456, 0.20352296])

In [33]:
gm.converged_

True

In [34]:
gm.n_iter_

17